name: DSW Web CI

on:
  push:
  pull_request:

jobs:
  btp:
    name: Build-Tag-Push
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.12.0]
    
    env:
      PRIVATE_IMAGE: ${{ secrets.PRIVATE_REGISTRY_URL }}/dsw-web
      TAG_LATEST: latest

    steps:
    - uses: actions/checkout@v2

# (1) -> Preparations
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install
      run: npm ci

# (2) -> Build
    - name: Build app
      run: |
        npm run build

    - name: Build Docker image
      run: |
        docker build -t $PRIVATE_IMAGE:$GITHUB_SHA .

# (3) -> Push Docker image
    - name: Docker login
      if: github.event_name == 'push'
      run: |
        docker login -u "$PRIVATE_REGISTRY_USERNAME" -p "$PRIVATE_REGISTRY_PASSWORD" "$PRIVATE_REGISTRY_URL"
      env:
        PRIVATE_REGISTRY_URL: ${{ secrets.PRIVATE_REGISTRY_URL }}
        PRIVATE_REGISTRY_USERNAME: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
        PRIVATE_REGISTRY_PASSWORD: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}

    - name: Docker tag and push - latest (private)
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        docker image tag $PRIVATE_IMAGE:$GITHUB_SHA $PRIVATE_IMAGE:$TAG_LATEST
        docker push $PRIVATE_IMAGE:$TAG_LATEST
